#!/usr/bin/ruby -sw

DB_DIR=ENV['HOME'] + '/work/shuravban.github.io/db'
LOG_DIR=DB_DIR + '/log'

def die(msg, code=1)
  $stderr.puts msg
  exit code
end

die "LOG_DIR: #{LOG_DIR} do not exist" if not File.directory? LOG_DIR

USAGE = <<END
Usage: #{File.basename $0} DESCRIPTION [FILES]
END

def usage(code=0)
  out = $stderr
  if code.zero?
    out = $stdin
  end
  out.puts USAGE
  exit code
end

usage 1 if ARGV.size.zero? or ARGV.size > 1

desc = ARGV.shift
rst = ARGF.read

time = Time.now.strftime '%Y%m%d-%H%M%S'
File.open(LOG_DIR + "/#{time}", "w") do |f|
  f.puts desc
  f.puts rst
  `cd #{LOG_DIR} && ln -f -s #{time} last`
end
